// Mocks generated by Mockito 5.4.6 from annotations
// in xai_translate/test/services/voice_input_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:xai_translate/services/voice_input_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WhisperClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWhisperClient extends _i1.Mock implements _i2.WhisperClient {
  MockWhisperClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> transcribe(String? audioPath) =>
      (super.noSuchMethod(
            Invocation.method(#transcribe, [audioPath]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#transcribe, [audioPath]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> isModelAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isModelAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [VoiceRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecorder extends _i1.Mock implements _i2.VoiceRecorder {
  MockVoiceRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> startRecording(String? outputPath) =>
      (super.noSuchMethod(
            Invocation.method(#startRecording, [outputPath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> stopRecording() =>
      (super.noSuchMethod(
            Invocation.method(#stopRecording, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#stopRecording, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  bool isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Stream<double> getAmplitudeStream() =>
      (super.noSuchMethod(
            Invocation.method(#getAmplitudeStream, []),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
